using Job.Core.Entitys;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Job.Core.Helper
{
    public static class SkillList
    {
        public static SkillsType[] GetSkillList()
        {
            return new SkillsType[]
            {
               new SkillsType { id = 1, TypeName = "C#" },
               new SkillsType { id = 2, TypeName = ".NET Core" },
               new SkillsType { id = 3, TypeName = "ASP.NET Core" },
               new SkillsType { id = 4, TypeName = "Entity Framework Core" },
               new SkillsType { id = 5, TypeName = "LINQ" },
               new SkillsType { id = 6, TypeName = "RESTful APIs" },
               new SkillsType { id = 7, TypeName = "Design Patterns" },
               new SkillsType { id = 8, TypeName = "SOLID Principles" },
               new SkillsType { id = 9, TypeName = "Dependency Injection" },
               new SkillsType { id = 10, TypeName = "SignalR" },
               new SkillsType { id = 11, TypeName = "Microservices" },
               new SkillsType { id = 12, TypeName = "Clean Architecture" },
               new SkillsType { id = 13, TypeName = "CQRS" },
               new SkillsType { id = 14, TypeName = "HTML" },
               new SkillsType { id = 15, TypeName = "CSS" },
               new SkillsType { id = 16, TypeName = "JavaScript" },
               new SkillsType { id = 17, TypeName = "TypeScript" },
               new SkillsType { id = 18, TypeName = "React" },
               new SkillsType { id = 19, TypeName = "Angular" },
               new SkillsType { id = 20, TypeName = "Vue.js" },
               new SkillsType { id = 21, TypeName = "Bootstrap" },
               new SkillsType { id = 22, TypeName = "Tailwind CSS" },
               new SkillsType { id = 23, TypeName = "Responsive Design" },
               new SkillsType { id = 24, TypeName = "UI/UX Design" },
               new SkillsType { id = 25, TypeName = "SQL Server" },
               new SkillsType { id = 26, TypeName = "MySQL" },
               new SkillsType { id = 27, TypeName = "PostgreSQL" },
               new SkillsType { id = 28, TypeName = "MongoDB" },
               new SkillsType { id = 29, TypeName = "Redis" },
               new SkillsType { id = 30, TypeName = "Database Design" },
               new SkillsType { id = 31, TypeName = "Query Optimization" },
               new SkillsType { id = 32, TypeName = "Data Analysis" },
               new SkillsType { id = 33, TypeName = "Git" },
               new SkillsType { id = 34, TypeName = "GitHub" },
               new SkillsType { id = 35, TypeName = "CI/CD" },
               new SkillsType { id = 36, TypeName = "Docker" },
               new SkillsType { id = 37, TypeName = "Kubernetes" },
               new SkillsType { id = 38, TypeName = "Azure" },
               new SkillsType { id = 39, TypeName = "AWS" },
               new SkillsType { id = 40, TypeName = "Linux" },
               new SkillsType { id = 41, TypeName = "Nginx" },
               new SkillsType { id = 42, TypeName = "IIS Deployment" },
               new SkillsType { id = 43, TypeName = "JWT" },
               new SkillsType { id = 44, TypeName = "OAuth 2.0" },
               new SkillsType { id = 45, TypeName = "Password Hashing" },
               new SkillsType { id = 46, TypeName = "HTTPS" },
               new SkillsType { id = 47, TypeName = "SQL Injection Prevention" },
               new SkillsType { id = 48, TypeName = "XSS Prevention" },
               new SkillsType { id = 49, TypeName = "Data Encryption" },
               new SkillsType { id = 50, TypeName = "Postman" },
               new SkillsType { id = 51, TypeName = "Swagger" },
               new SkillsType { id = 52, TypeName = "Visual Studio" },
               new SkillsType { id = 53, TypeName = "VS Code" },
               new SkillsType { id = 54, TypeName = "Figma" },
               new SkillsType { id = 55, TypeName = "Trello" },
               new SkillsType { id = 56, TypeName = "Jira" },
               new SkillsType { id = 57, TypeName = "Problem Solving" },
               new SkillsType { id = 58, TypeName = "Teamwork" },
               new SkillsType { id = 59, TypeName = "Communication" },
               new SkillsType { id = 60, TypeName = "Time Management" },
               new SkillsType { id = 61, TypeName = "Adaptability" },
               new SkillsType { id = 62, TypeName = "Critical Thinking" },
               new SkillsType { id = 63, TypeName = "Creativity" },
               new SkillsType { id = 64, TypeName = "Attention to Detail" },
               new SkillsType { id = 65, TypeName = "Leadership" },
               new SkillsType { id = 66, TypeName = "Work Under Pressure" },
               new SkillsType { id = 67, TypeName = "Continuous Learning" },
               new SkillsType { id = 68, TypeName = "Self-Motivation" },
               new SkillsType { id = 69, TypeName = "Decision Making" },
               new SkillsType { id = 70, TypeName = "Responsibility" },
               new SkillsType { id = 71, TypeName = "Project Management" },
               new SkillsType { id = 72, TypeName = "Business Analysis" },
               new SkillsType { id = 73, TypeName = "Strategic Planning" },
               new SkillsType { id = 74, TypeName = "Operations Management" },
               new SkillsType { id = 75, TypeName = "Team Leadership" },
               new SkillsType { id = 76, TypeName = "Customer Service" },
               new SkillsType { id = 77, TypeName = "Negotiation" },
               new SkillsType { id = 78, TypeName = "Sales" },
               new SkillsType { id = 79, TypeName = "Financial Management" },
               new SkillsType { id = 80, TypeName = "Digital Marketing" },
               new SkillsType { id = 81, TypeName = "Social Media Marketing" },
               new SkillsType { id = 82, TypeName = "Content Writing" },
               new SkillsType { id = 83, TypeName = "Copywriting" },
               new SkillsType { id = 84, TypeName = "SEO (Search Engine Optimization)" },
               new SkillsType { id = 85, TypeName = "Email Marketing" },
               new SkillsType { id = 86, TypeName = "Advertising Campaigns" },
               new SkillsType { id = 87, TypeName = "Brand Management" },
               new SkillsType { id = 88, TypeName = "Market Research" },
               new SkillsType { id = 89, TypeName = "Graphic Design" },
               new SkillsType { id = 90, TypeName = "Video Editing" },
               new SkillsType { id = 91, TypeName = "Photography" },
               new SkillsType { id = 92, TypeName = "Illustration" },
               new SkillsType { id = 93, TypeName = "Motion Graphics" },
               new SkillsType { id = 94, TypeName = "UI Design" },
               new SkillsType { id = 95, TypeName = "UX Design" },
               new SkillsType { id = 96, TypeName = "Canva" },
               new SkillsType { id = 97, TypeName = "Adobe Photoshop" },
               new SkillsType { id = 98, TypeName = "Adobe Illustrator" },
               new SkillsType { id = 99, TypeName = "Adobe Premiere Pro" },
               new SkillsType { id = 100, TypeName = "After Effects" },
               new SkillsType { id = 101, TypeName = "Public Speaking" },
               new SkillsType { id = 102, TypeName = "Networking" },
               new SkillsType { id = 103, TypeName = "Negotiation Skills" },
               new SkillsType { id = 104, TypeName = "Customer Relationship Management" },
               new SkillsType { id = 105, TypeName = "Conflict Resolution" },
               new SkillsType { id = 106, TypeName = "Presentation Skills" },
               new SkillsType { id = 107, TypeName = "Time Management" },
               new SkillsType { id = 108, TypeName = "Self-Discipline" },
               new SkillsType { id = 109, TypeName = "Adaptability" },
               new SkillsType { id = 110, TypeName = "Problem Solving" },
               new SkillsType { id = 111, TypeName = "Creativity" },
               new SkillsType { id = 112, TypeName = "Critical Thinking" },
               new SkillsType { id = 113, TypeName = "Decision Making" },
               new SkillsType { id = 114, TypeName = "Attention to Detail" },
               new SkillsType { id = 115, TypeName = "Work Under Pressure" },
               new SkillsType { id = 116, TypeName = "Translation" },
               new SkillsType { id = 117, TypeName = "Typing" },
               new SkillsType { id = 118, TypeName = "Microsoft Word" },
               new SkillsType { id = 119, TypeName = "Microsoft Excel" },
               new SkillsType { id = 120, TypeName = "Microsoft PowerPoint" },
               new SkillsType { id = 121, TypeName = "Google Workspace" },
               new SkillsType { id = 122, TypeName = "Backend Develper" },
               new SkillsType { id = 123, TypeName = "Frontend Developer"}
            };
        }
    }
}
